### ISSUE TITLE
Create issue for error messages

### ISSUE THREAD

**Issue by dan89farhan** [dan89farhan/whatsAppMarketing-Issue#8]
Currently showing the default error page for showing error. please create a new error page.
Error: campaign not found.
    at /home/farhan/nodejsproject/whatsapp-api-test/routes/reportRouter.js:10:23
    at /home/farhan/nodejsproject/whatsapp-api-test/node_modules/mongoose/lib/model.js:4834:16
    at /home/farhan/nodejsproject/whatsapp-api-test/node_modules/mongoose/lib/model.js:4834:16
    at /home/farhan/nodejsproject/whatsapp-api-test/node_modules/mongoose/lib/helpers/promiseOrCallback.js:24:16
    at /home/farhan/nodejsproject/whatsapp-api-test/node_modules/mongoose/lib/model.js:4857:21
    at _hooks.execPost (/home/farhan/nodejsproject/whatsapp-api-test/node_modules/mongoose/lib/query.js:4390:11)
    at /home/farhan/nodejsproject/whatsapp-api-test/node_modules/kareem/index.js:135:16
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by dan89farhan** [comment]
Ismail please look into it @webismail92

**Comment by dan89farhan** [comment]
since we changed the technology stack therefore it is not required anymore
